#!/bin/sh

. $GIT_DIR/hooks/hooks.conf

echo 'Backing up database'
vagrant ssh -c "drush sql-dump -r $PROJECT_PATH_GUEST --result-file=/$PROJECT_PATH_GUEST/database-backup.sql"
status=$?
if [ $status -ne 0 ]; then
   echo "Could not connect to the guest through SSH"
   exit 1
else
  echo 'Done'
  git add -u $GIT_DIR/../$PROJECT_PATH_HOST/database-backup.sql
  exit 0
fi
